# Generated by Django 5.1.7 on 2025-04-19 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('membership_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'membership',
            },
        ),
        migrations.CreateModel(
            name='MemberAddress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('street_address', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('membership', models.ForeignKey(db_column='Membership_id', on_delete=django.db.models.deletion.CASCADE, to='customer.membership')),
            ],
            options={
                'db_table': 'member_address',
                'unique_together': {('membership', 'city', 'province', 'street_address', 'postal_code')},
            },
        ),
    ]
