# Generated by Django 5.1.7 on 2025-04-19 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('employee', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField()),
                ('delivery_address', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('order_status', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_notes', models.TextField(blank=True, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('employee', models.ForeignKey(blank=True, db_column='Employee_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.salesperson')),
                ('member', models.ForeignKey(blank=True, db_column='Member_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.membership')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_id', models.IntegerField()),
                ('quantity_ordered', models.IntegerField()),
                ('product', models.ForeignKey(blank=True, db_column='Product_id', null=True, on_delete=django.db.models.deletion.RESTRICT, to='product.product')),
                ('order', models.ForeignKey(db_column='Order_id', on_delete=django.db.models.deletion.CASCADE, to='order.orders')),
            ],
            options={
                'db_table': 'order_item',
                'unique_together': {('order', 'item_id')},
            },
        ),
    ]
