# Generated by Django 5.1.7 on 2025-03-30 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('salary', models.FloatField(blank=True, null=True)),
                ('login_password', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('street_address', models.CharField(max_length=255)),
                ('post_code', models.CharField(max_length=7)),
            ],
            options={
                'db_table': 'employee_address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PurchasepersonManagerManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'purchaseperson_manager_management',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SalespersonManagerManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'salesperson_manager_management',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='employee.employee')),
                ('management_level', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'manager',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PurchasePerson',
            fields=[
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='employee.employee')),
                ('purchase_section', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'purchase_person',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salesperson',
            fields=[
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='employee.employee')),
                ('sales_target', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'salesperson',
                'managed': False,
            },
        ),
    ]
