# Generated by Django 5.1.7 on 2025-04-19 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('login_password', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.PositiveSmallIntegerField(choices=[(0, 'Salesperson'), (1, 'Purchaseperson'), (2, 'Manager')], default=0)),
                ('supervisor', models.ForeignKey(blank=True, db_column='Supervisor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='employee.employee')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('employee', models.OneToOneField(db_column='Employee_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='employee.employee')),
                ('management_level', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'manager',
            },
        ),
        migrations.CreateModel(
            name='PurchasePerson',
            fields=[
                ('employee', models.OneToOneField(db_column='Employee_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='employee.employee')),
                ('purchase_section', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'purchase_person',
            },
        ),
        migrations.CreateModel(
            name='Salesperson',
            fields=[
                ('employee', models.OneToOneField(db_column='Employee_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='employee.employee')),
                ('sales_target', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'salesperson',
            },
        ),
        migrations.CreateModel(
            name='EmployeeAddress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('province', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('street_address', models.CharField(max_length=255)),
                ('post_code', models.CharField(max_length=7)),
                ('employee', models.ForeignKey(db_column='Employee_id', on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'db_table': 'employee_address',
                'unique_together': {('employee', 'province', 'city', 'street_address', 'post_code')},
            },
        ),
    ]
