# Generated by Django 5.1.7 on 2025-04-18 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeaddress',
            options={'managed': True},
        ),
    ]
