# Generated by Django 5.1.7 on 2025-04-21 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_rename_employee_id_employee_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='id',
            new_name='employee_id',
        ),
    ]
