# Generated by Django 5.1.7 on 2025-04-18 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employeeaddress_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeaddress',
            options={'managed': False},
        ),
    ]
