# Generated by Django 5.1.7 on 2025-04-21 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_rename_id_employee_employee_id'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorypurchase',
            name='employee',
            field=models.ForeignKey(blank=True, db_column='Employee_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.purchaseperson'),
        ),
        migrations.AlterField(
            model_name='inventorypurchase',
            name='purchase_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
