# Generated by Django 5.1.7 on 2025-04-22 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_after_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='FoodProduct',
            fields=[
                ('product', models.OneToOneField(db_column='Product_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='product.product')),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('storage_condition', models.CharField(blank=True, max_length=50, null=True)),
                ('food_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'food_product',
            },
        ),
        migrations.CreateModel(
            name='NonFoodProduct',
            fields=[
                ('product', models.OneToOneField(db_column='Product_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='product.product')),
                ('brand', models.CharField(blank=True, max_length=99, null=True)),
                ('warranty_period', models.CharField(blank=True, max_length=99, null=True)),
            ],
            options={
                'db_table': 'non_food_product',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inventory_id', models.IntegerField()),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.CharField(blank=True, max_length=50, null=True)),
                ('product', models.ForeignKey(db_column='Product_id', on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'db_table': 'inventory',
                'unique_together': {('product', 'inventory_id')},
            },
        ),
    ]
