# Generated by Django 5.1.7 on 2025-04-21 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplieraddress',
            name='supplier',
            field=models.ForeignKey(db_column='Supplier_id', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='supplier.supplier'),
        ),
    ]
